version: "3"
services:
  server:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/go/src/user-auth/
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: go_user

  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: go_user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    links:
      - mysql
    ports:
      - 8888:80